/**
 * Auto-generated from `apps/game/gameActionFactory.js`
 * Action: `PlayerEnteredChunk`
 * Source field enum: `XT`
 */
export enum PlayerEnteredChunkFields {
  EntityID = 0,
  EntityTypeID = 1,
  PlayerType = 2,
  Username = 3,
  CombatLevel = 4,
  HitpointsLevel = 5,
  CurrentHitpointsLevel = 6,
  MapLevel = 7,
  X = 8,
  Y = 9,
  HairStyleID = 10,
  BeardStyleID = 11,
  ShirtID = 12,
  BodyTypeID = 13,
  LegsID = 14,
  EquipmentHeadID = 15,
  helmet = 16,
  EquipmentBodyID = 17,
  chest = 18,
  EquipmentLegsID = 19,
  legs = 20,
  EquipmentBootsID = 21,
  boots = 22,
  EquipmentNecklaceID = 23,
  neck = 24,
  EquipmentWeaponID = 25,
  weapon = 26,
  EquipmentShieldID = 27,
  shield = 28,
  EquipmentBackPackID = 29,
  back = 30,
  EquipmentGlovesID = 31,
  gloves = 32,
  EquipmentProjectileID = 33,
  projectile = 34,
  CurrentState = 35,
  MentalClarity = 36,
}
